repos:
  - repo: local
    hooks:
      - id: black
        name: black
        language: system
        entry: black
        require_serial: true
        types: [python]
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]
        require_serial: true
      - id: isort
        name: isort
        entry: isort
        require_serial: true
        language: python
        types: [python]
      - id: mypy
        name: mypy
        entry: mypy
        language: python
        types: [python]
        exclude: setup.py
        require_serial: true
